[package]
name = "nitro"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = {version="3.1.6", features=["derive"]}
walkdir = "2.3.2"
ring = "0.17.0-alpha.11"
data-encoding = "2.3.2"
sled = "0.34.7"
tokio = { version = "1.17.0", features = ["full"] }
lettre = "0.10.0-beta.2"
serde = { version = "1.0.136", features = ["derive"] }
serde_yaml = "0.8.23"
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
log = "0.4.16"
env_logger = "0.9.0"
regex = "1.5.5"
indicatif = "0.16.2"
