name: build debian package

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:

  publish-build-debian-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup nightly
      run: rustup default nightly
    - name: install cargo-deb
      run: cargo install cargo-deb
    - name: Build
      run: cargo deb
    - name: upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: snitch_deb
        path: target/debian/*
