name: build OSX

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:

  release-osx:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Release
      run: cargo build --release
    - name: Rename artifact
      run: cp target/release/snitch target/release/snitch-osx

    - name: upload artefact
      uses: actions/upload-artifact@v3
      with:
        name: snitch-osx
        path: target/release/snitch-osx

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/release/snitch-osx
