name: Release on crates.io

on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'

env:
  CARGO_TERM_COLOR: always
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

jobs:

  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  publish-crates-io:
    runs-on: ubuntu-latest
    needs:
      - build-and-test
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: cargo login
      run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
    - name: cargo publish
      run: cargo publish
