name: Rust

on:
  push:
    branches: [ main ]
    tags-ignore:
      - '*.*.*'
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
  SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  test-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup nightly
      run: rustup default nightly
    - name: Build
      run: cargo build --verbose
    - name: Run app init
      run: cargo run -- --init --config-file=.github/workflows/testconfig.yaml
    - name: Run app scan
      run: cargo run -- --scan --config-file=.github/workflows/testconfig.yaml
